using System;
using MRuby;
using MRuby.CodeGen;

class Program
{
    static void Main(string[] args)
    {
        var mrubyTypes = CodeGenUtil.GetMRubyClasses(new string[] { "MRubyLib"});
        foreach( var t in mrubyTypes)
        {
            Console.WriteLine(t);
        }

        var reg = new Registry();
        var path = "../CodeGenTest/AutoGenerated/";
        foreach( var t in mrubyTypes)
        {
            CodeGenUtil.Generate(reg, t, "", path);
        }
        CodeGenUtil.GenerateBind(reg, path);
        Console.WriteLine("Generated");
    }
}
